export const DATE_FORMAT = 'YYYY MM DD HH:mm:ss ZZ';

export const SHIP_TYPES = {
  barge: 'Barge',
  bleeder: 'Bleeder',
  cargo_ship: 'Cargo Ship',
  colony_ship: 'Colony Ship',
  detonator: 'Detonator',
  dory: 'Dory',
  drone: 'Drone',
  excavator: 'Excavator',
  fighter: 'Fighter',
  fissure_sealer: 'Fissure Sealer',
  freighter: 'Freighter',
  galleon: 'Galleon',
  gas_giant_settlement_ship: 'Gas Giant Settlement Ship',
  hulk_fast: 'Hulk Fast',
  hulk_huge: 'Hulk Huge',
  hulk: 'Hulk',
  mining_platform_ship: 'Mining Platform Ship',
  observatory_seeker: 'observatory Seeker',
  placebo: 'Nocebo',
  placebo2: 'Nocebo II',
  placebo3: 'Nocebo III',
  placebo4: 'Nocebo IV',
  placebo5: 'Nocebo V',
  placebo6: 'Nocebo VI',
  probe: 'probe',
  scanner: 'Scanner',
  scow_fast: 'Scow Fast',
  scow_large: 'Scow Large',
  scow_mega: 'Scow Mega',
  scow: 'Scow',
  security_ministry_seeker: 'Security Ministry Seeker',
  short_range_colony_ship: 'Short Range Colony Ship',
  smuggler_ship: 'Smuggler Ship',
  snark: 'Snark',
  snark2: 'Snark II',
  snark3: 'Snark III',
  space_station: 'Space Station',
  spaceport_seeker: 'Spaceport Seeker',
  spy_pod: 'Spy Pod',
  spy_shuttle: 'Spy Shuttle',
  stake: 'Stake',
  supply_pod: 'Supply Pod',
  supply_pod2: 'Supply Pod II',
  supply_pod3: 'Supply Pod III',
  supply_pod4: 'Supply Pod IV',
  supply_pod5: 'Supply Pod V',
  surveyor: 'Surveyor',
  sweeper: 'Sweeper',
  terraforming_platform_ship: 'Terraforming Platform Ship',
  thud: 'Thud',
};
