import Body from './modules/body.js';
import Buildings from './modules/buildings.js';
import Captcha from './modules/captcha.js';
import Development from './modules/development.js';
import Empire from './modules/empire.js';
import EnergyReserve from './modules/energyReserve.js';
import EssentiaVein from './modules/essentiaVein.js';
import FoodReserve from './modules/foodReserve.js';
import GenericBuilding from './modules/genericBuilding.js';
import Inbox from './modules/inbox.js';
import Intelligence from './modules/intelligence.js';
import IntelTraining from './modules/intelTraining.js';
import Map from './modules/map.js';
import MayhemTraining from './modules/mayhemTraining.js';
import OreStorage from './modules/oreStorage.js';
import PoliticsTraining from './modules/politicsTraining.js';
import Server from './modules/server.js';
import Shipyard from './modules/shipyard.js';
import Spaceport from './modules/spaceport.js';
import Stats from './modules/stats.js';
import TheftTraining from './modules/theftTraining.js';
import WaterStorage from './modules/waterStorage.js';
import SpaceStationLab from './modules/spaceStationLab.js';

import { RouteMapping } from './interfaces.js';

const Routes: RouteMapping = {
  body: Body,
  buildings: Buildings,
  captcha: Captcha,
  empire: Empire,
  inbox: Inbox,
  map: Map,
  server: Server,
  stats: Stats,

  //
  // Buildings
  //
  algae: GenericBuilding,
  algaepond: GenericBuilding,
  alliance: GenericBuilding,
  amalgusmeadow: GenericBuilding,
  apple: GenericBuilding,
  archaeology: GenericBuilding,
  artmuseum: GenericBuilding,
  atmosphericevaporator: GenericBuilding,
  beach: GenericBuilding,
  bean: GenericBuilding,
  beeldeban: GenericBuilding,
  beeldebannest: GenericBuilding,
  blackholegenerator: GenericBuilding,
  bread: GenericBuilding,
  burger: GenericBuilding,
  capitol: GenericBuilding,
  cheese: GenericBuilding,
  chip: GenericBuilding,
  cider: GenericBuilding,
  citadelofknope: GenericBuilding,
  cloakinglab: GenericBuilding,
  corn: GenericBuilding,
  cornmeal: GenericBuilding,
  crashedshipsite: GenericBuilding,
  crater: GenericBuilding,
  culinaryinstitute: GenericBuilding,
  dairy: GenericBuilding,
  denton: GenericBuilding,
  dentonbrambles: GenericBuilding,
  deployedbleeder: GenericBuilding,
  development: Development,
  distributioncenter: GenericBuilding,
  embassy: GenericBuilding,
  energyreserve: EnergyReserve,
  entertainment: GenericBuilding,
  espionage: GenericBuilding,
  essentiavein: EssentiaVein,
  fission: GenericBuilding,
  fissure: GenericBuilding,
  foodreserve: FoodReserve,
  fusion: GenericBuilding,
  gasgiantlab: GenericBuilding,
  gasgiantplatform: GenericBuilding,
  geneticslab: GenericBuilding,
  geo: GenericBuilding,
  geothermalvent: GenericBuilding,
  gratchsgauntlet: GenericBuilding,
  greatballofjunk: GenericBuilding,
  grove: GenericBuilding,
  hallsofvrbansk: GenericBuilding,
  hydrocarbon: GenericBuilding,
  ibs: GenericBuilding,
  intelligence: Intelligence,
  inteltraining: IntelTraining,
  interdimensionalrift: GenericBuilding,
  junkhengesculpture: GenericBuilding,
  kalavianruins: GenericBuilding,
  kasternskeep: GenericBuilding,
  lagoon: GenericBuilding,
  lake: GenericBuilding,
  lapis: GenericBuilding,
  lapisforest: GenericBuilding,
  lcota: GenericBuilding,
  lcotb: GenericBuilding,
  lcotc: GenericBuilding,
  lcotd: GenericBuilding,
  lcote: GenericBuilding,
  lcotf: GenericBuilding,
  lcotg: GenericBuilding,
  lcoth: GenericBuilding,
  lcoti: GenericBuilding,
  libraryofjith: GenericBuilding,
  luxuryhousing: GenericBuilding,
  malcud: GenericBuilding,
  malcudfield: GenericBuilding,
  massadshenge: GenericBuilding,
  mayhemtraining: MayhemTraining,
  mercenariesguild: GenericBuilding,
  metaljunkarches: GenericBuilding,
  mine: GenericBuilding,
  miningministry: GenericBuilding,
  missioncommand: GenericBuilding,
  munitionslab: GenericBuilding,
  naturalspring: GenericBuilding,
  network19: GenericBuilding,
  observatory: GenericBuilding,
  operahouse: GenericBuilding,
  oracleofanid: GenericBuilding,
  orerefinery: GenericBuilding,
  orestorage: OreStorage,
  oversight: GenericBuilding,
  pancake: GenericBuilding,
  pantheonofhagness: GenericBuilding,
  park: GenericBuilding,
  parliament: GenericBuilding,
  pie: GenericBuilding,
  pilottraining: GenericBuilding,
  planetarycommand: GenericBuilding,
  policestation: GenericBuilding,
  politicstraining: PoliticsTraining,
  potato: GenericBuilding,
  propulsion: GenericBuilding,
  pyramidjunksculpture: GenericBuilding,
  ravine: GenericBuilding,
  rockyoutcrop: GenericBuilding,
  sand: GenericBuilding,
  saw: GenericBuilding,
  security: GenericBuilding,
  shake: GenericBuilding,
  shipyard: Shipyard,
  singularity: GenericBuilding,
  soup: GenericBuilding,
  spacejunkpark: GenericBuilding,
  spaceport: Spaceport,
  ssla: SpaceStationLab,
  sslb: GenericBuilding,
  sslc: GenericBuilding,
  ssld: GenericBuilding,
  stationcommand: GenericBuilding,
  stockpile: GenericBuilding,
  subspacesupplydepot: GenericBuilding,
  supplypod: GenericBuilding,
  syrup: GenericBuilding,
  templeofthedrajilites: GenericBuilding,
  terraforminglab: GenericBuilding,
  terraformingplatform: GenericBuilding,
  thedillonforge: GenericBuilding,
  thefttraining: TheftTraining,
  themepark: GenericBuilding,
  trade: GenericBuilding,
  transporter: GenericBuilding,
  university: GenericBuilding,
  volcano: GenericBuilding,
  warehouse: GenericBuilding,
  wastedigester: GenericBuilding,
  wasteenergy: GenericBuilding,
  wasteexchanger: GenericBuilding,
  wasterecycling: GenericBuilding,
  wastesequestration: GenericBuilding,
  wastetreatment: GenericBuilding,
  waterproduction: GenericBuilding,
  waterpurification: GenericBuilding,
  waterreclamation: GenericBuilding,
  waterstorage: WaterStorage,
  wheat: GenericBuilding,
};

export default Routes;
