'use strict';

const { Server } = require('miragejs');

const handleResponse = (module, response) => {
    const json = JSON.parse(response.requestBody);
    console.log(`/${module}/${json.method}`, json.params);
    return {
        method: json.method,
        params: json.params,
    };
};

const body_get_buildings = () => {
    return {
        status: get_status(),
        body: {
            surface_image: 'surface-p35',
        },
        buildings: {
            '4965708': {
                efficiency: '100',
                name: 'Black Hole Generator',
                x: '1',
                image: 'blackholegenerator1',
                y: '4',
                level: '30',
                url: '/blackholegenerator',
            },
            '4942253': {
                y: '4',
                efficiency: '100',
                level: '30',
                name: 'Water Storage Tank',
                url: '/waterstorage',
                x: '-3',
                image: 'waterstorage9',
            },
            '4965699': {
                y: '4',
                efficiency: '100',
                level: '30',
                name: 'Pyramid Junk Sculpture',
                url: '/pyramidjunksculpture',
                x: '-5',
                image: 'pyramidjunksculpture1',
            },
            spacejunkpark: {
                y: '4',
                efficiency: '100',
                level: '30',
                name: 'Space Junk Park',
                url: '/spacething',
                x: '-4',
                image: 'spacejunkpark1',
            },
            arches: {
                y: '3',
                efficiency: '100',
                level: '30',
                name: 'Metal Junk Arches',
                url: '/metal',
                x: '-5',
                image: 'metaljunkarches1',
            },
            henge: {
                y: '3',
                efficiency: '100',
                level: '30',
                name: 'Junk Henge',
                url: '/junkhenge',
                x: '-4',
                image: 'junkhengesculpture1',
            },
            greatballofjunk: {
                y: '3',
                efficiency: '100',
                level: '30',
                name: 'Great Ball of Junk',
                url: '/ball',
                x: '-3',
                image: 'greatballofjunk1',
            },
            panth: {
                y: '4',
                efficiency: '100',
                level: '30',
                name: 'Panth',
                url: '/panth',
                x: '0',
                image: 'pantheonofhagness1',
            },
            temple: {
                y: '4',
                efficiency: '100',
                level: '30',
                name: 'Temple',
                url: '/temple',
                x: '3',
                image: 'templedrajilites1',
            },
            '4943197': {
                y: '2',
                efficiency: '100',
                level: '30',
                name: 'Intelligence Ministry',
                url: '/intelligence',
                x: '1',
                image: 'intelligence9',
            },
            '4979713': {
                y: '0',
                efficiency: '100',
                level: '30',
                name: 'Shield Against Weapons',
                url: '/saw',
                x: '3',
                image: 'saw9',
            },
            '4944689': {
                y: '-1',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-5',
                image: 'spaceport9',
            },
            '4943183': {
                y: '-1',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '0',
                image: 'spaceport9',
            },
            '4979712': {
                y: '0',
                efficiency: '100',
                level: '30',
                name: 'Shield Against Weapons',
                url: '/saw',
                x: '2',
                image: 'saw9',
            },
            '4944680': {
                y: '5',
                efficiency: '100',
                level: '30',
                name: 'Interdimensional Rift',
                url: '/interdimensionalrift',
                x: '0',
                image: 'interdimensionalrift1',
            },
            '4942254': {
                y: '4',
                efficiency: '100',
                level: '30',
                name: 'Energy Reserve',
                url: '/energyreserve',
                x: '-2',
                image: 'energy-reserve9',
            },
            '4944683': {
                y: '4',
                efficiency: '100',
                level: '30',
                name: 'Crashed Ship Site',
                url: '/crashedshipsite',
                x: '-1',
                image: 'crashedshipsite1',
            },
            '4948857': {
                efficiency: '100',
                name: 'Propulsion System Factory',
                x: '-2',
                image: 'propulsion9',
                y: '2',
                level: '30',
                url: '/propulsion',
            },
            '4944213': {
                y: '5',
                efficiency: '100',
                level: '30',
                name: 'Archaeology Ministry',
                url: '/archaeology',
                x: '2',
                image: 'archaeology9',
            },
            '4943640': {
                y: '5',
                efficiency: '100',
                level: '30',
                name: 'Geo Thermal Vent',
                url: '/geothermalvent',
                x: '-2',
                image: 'geothermalvent1',
            },
            '4968807': {
                y: '2',
                efficiency: '100',
                level: '30',
                name: 'Entertainment District',
                url: '/entertainment',
                x: '1',
                image: 'entertainment1',
            },
            '4975914': {
                y: '-2',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-1',
                image: 'spaceport9',
            },
            '4976222': {
                y: '-2',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-3',
                image: 'spaceport9',
            },
            '4948858': {
                efficiency: '100',
                name: 'Pilot Training Facility',
                x: '-3',
                image: 'pilottraining9',
                y: '2',
                level: '30',
                url: '/pilottraining',
            },
            '4943281': {
                y: '3',
                efficiency: '100',
                level: '30',
                name: 'Observatory',
                url: '/observatory',
                x: '-2',
                image: 'observatory9',
            },
            '4942247': {
                y: '3',
                efficiency: '100',
                level: '30',
                name: 'University',
                url: '/university',
                x: '3',
                image: 'university9',
            },
            '4944685': {
                y: '-1',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-1',
                image: 'spaceport9',
            },
            '4944198': {
                efficiency: '100',
                name: 'Trade Ministry',
                x: '0',
                image: 'trade9',
                y: '2',
                level: '30',
                url: '/trade',
            },
            '4943639': {
                y: '5',
                efficiency: '100',
                level: '30',
                name: 'Natural Spring',
                url: '/naturalspring',
                x: '-3',
                image: 'naturalspring1',
            },
            '4944677': {
                y: '5',
                efficiency: '100',
                level: '30',
                name: 'Development Ministry',
                url: '/development',
                x: '1',
                image: 'devel9',
            },
            '4979716': {
                y: '0',
                efficiency: '100',
                level: '30',
                name: 'Shield Against Weapons',
                url: '/saw',
                x: '5',
                image: 'saw9',
            },
            '4979714': {
                y: '0',
                efficiency: '100',
                level: '30',
                name: 'Shield Against Weapons',
                url: '/saw',
                x: '4',
                image: 'saw9',
            },
            '4943633': {
                y: '5',
                efficiency: '100',
                level: '30',
                name: 'Volcano',
                url: '/volcano',
                x: '-4',
                image: 'volcano1',
            },
            '4944687': {
                y: '-1',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-3',
                image: 'spaceport9',
            },
            '4976223': {
                y: '-2',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-4',
                image: 'spaceport9',
            },
            '4944678': {
                y: '5',
                efficiency: '100',
                level: '30',
                name: 'Oversight Ministry',
                url: '/oversight',
                x: '3',
                image: 'oversight9',
            },
            '4944681': {
                y: '5',
                efficiency: '100',
                level: '30',
                name: 'Kalavian Ruins',
                url: '/kalavianruins',
                x: '-1',
                image: 'kalavianruins1',
            },
            '4942219': {
                y: '0',
                efficiency: '100',
                level: '30',
                name: 'Planetary Command Center',
                url: '/planetarycommand',
                x: '0',
                image: 'command9',
            },
            '4976350': {
                y: '-2',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-5',
                image: 'spaceport9',
            },
            '4970232': {
                efficiency: '100',
                name: 'Munitions Lab',
                x: '-4',
                image: 'munitionslab6',
                y: '2',
                level: '30',
                url: '/munitionslab',
            },
            '4943631': {
                y: '5',
                efficiency: '100',
                level: '30',
                name: 'Malcud Field',
                url: '/malcudfield',
                x: '-5',
                image: 'malcudfield1',
            },
            '4970063': {
                efficiency: '100',
                name: 'Espionage Ministry',
                x: '2',
                image: 'espionage9',
                y: '2',
                level: '30',
                url: '/espionage',
            },
            '4968550': {
                efficiency: '100',
                name: 'Cloaking Lab',
                x: '-5',
                image: 'cloakinglab9',
                y: '2',
                level: '30',
                url: '/cloakinglab',
            },
            '4944686': {
                y: '-1',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-2',
                image: 'spaceport9',
            },
            '4976221': {
                y: '-2',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-2',
                image: 'spaceport9',
            },
            '4975891': {
                y: '-2',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '0',
                image: 'spaceport9',
            },
            '4979711': {
                y: '0',
                efficiency: '100',
                level: '30',
                name: 'Shield Against Weapons',
                url: '/saw',
                x: '1',
                image: 'saw9',
            },
            'saw-1': {
                y: '0',
                efficiency: '100',
                level: '30',
                name: 'Shield Against Weapons',
                url: '/saw',
                x: '-1',
                image: 'saw9',
            },
            'saw-2': {
                y: '0',
                efficiency: '100',
                level: '30',
                name: 'Shield Against Weapons',
                url: '/saw',
                x: '-2',
                image: 'saw9',
            },
            'saw-3': {
                y: '0',
                efficiency: '100',
                level: '30',
                name: 'Shield Against Weapons',
                url: '/saw',
                x: '-3',
                image: 'saw9',
            },
            'saw-4': {
                y: '0',
                efficiency: '100',
                level: '30',
                name: 'Shield Against Weapons',
                url: '/saw',
                x: '-4',
                image: 'saw9',
            },
            'saw-5': {
                y: '0',
                efficiency: '100',
                level: '30',
                name: 'Shield Against Weapons',
                url: '/saw',
                x: '-5',
                image: 'saw9',
            },
            '4966153': {
                efficiency: '100',
                name: 'Security Ministry',
                x: '3',
                image: 'security9',
                y: '2',
                level: '30',
                url: '/security',
            },
            ship5: {
                efficiency: '100',
                name: 'Shipyard',
                x: '5',
                image: 'shipyard9',
                y: '1',
                level: '30',
                url: '/shipyard',
            },
            ship4: {
                efficiency: '100',
                name: 'Shipyard',
                x: '4',
                image: 'shipyard9',
                y: '1',
                level: '30',
                url: '/shipyard',
            },
            ship3: {
                efficiency: '100',
                name: 'Shipyard',
                x: '3',
                image: 'shipyard9',
                y: '1',
                level: '30',
                url: '/shipyard',
            },
            ship2: {
                efficiency: '100',
                name: 'Shipyard',
                x: '2',
                image: 'shipyard9',
                y: '1',
                level: '30',
                url: '/shipyard',
            },
            ship1: {
                efficiency: '100',
                name: 'Shipyard',
                x: '1',
                image: 'shipyard9',
                y: '1',
                level: '30',
                url: '/shipyard',
            },
            ship0: {
                efficiency: '100',
                name: 'Shipyard',
                x: '0',
                image: 'shipyard9',
                y: '1',
                level: '30',
                url: '/shipyard',
            },
            'ship-1': {
                efficiency: '100',
                name: 'Shipyard',
                x: '-1',
                image: 'shipyard9',
                y: '1',
                level: '30',
                url: '/shipyard',
            },
            'ship-2': {
                efficiency: '100',
                name: 'Shipyard',
                x: '-2',
                image: 'shipyard9',
                y: '1',
                level: '30',
                url: '/shipyard',
            },
            'ship-3': {
                efficiency: '100',
                name: 'Shipyard',
                x: '-3',
                image: 'shipyard9',
                y: '1',
                level: '30',
                url: '/shipyard',
            },
            'ship1-4': {
                efficiency: '100',
                name: 'Shipyard',
                x: '-4',
                image: 'shipyard9',
                y: '1',
                level: '30',
                url: '/shipyard',
            },
            'ship-5': {
                efficiency: '100',
                name: 'Shipyard',
                x: '-5',
                image: 'shipyard9',
                y: '1',
                level: '30',
                url: '/shipyard',
            },
            '4944688': {
                y: '-1',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-4',
                image: 'spaceport9',
            },
            '4947856': {
                y: '4',
                efficiency: '100',
                level: '30',
                name: 'Oracle of Anid',
                url: '/oracleofanid',
                x: '2',
                image: 'oracleanid1',
            },
            '4943604': {
                y: '2',
                efficiency: '100',
                level: '30',
                name: 'Subspace Transporter',
                url: '/transporter',
                x: '-1',
                image: 'transporter9',
            },
            'port5,-1': {
                y: '-1',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '5',
                image: 'spaceport9',
            },
            'port5,-2': {
                y: '-2',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '5',
                image: 'spaceport9',
            },
            'port5,-3': {
                y: '-3',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '5',
                image: 'spaceport9',
            },
            'port5,-4': {
                y: '-4',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '5',
                image: 'spaceport9',
            },
            'port5,-5': {
                y: '-5',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '5',
                image: 'spaceport9',
            },
            'port4,-1': {
                y: '-1',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '4',
                image: 'spaceport9',
            },
            'port4,-2': {
                y: '-2',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '4',
                image: 'spaceport9',
            },
            'port4,-3': {
                y: '-3',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '4',
                image: 'spaceport9',
            },
            'port4,-4': {
                y: '-4',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '4',
                image: 'spaceport9',
            },
            'port4,-5': {
                y: '-5',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '4',
                image: 'spaceport9',
            },
            'port3,-1': {
                y: '-1',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '3',
                image: 'spaceport9',
            },
            'port3,-2': {
                y: '-2',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '3',
                image: 'spaceport9',
            },
            'port3,-3': {
                y: '-3',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '3',
                image: 'spaceport9',
            },
            'port3,-4': {
                y: '-4',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '3',
                image: 'spaceport9',
            },
            'port3,-5': {
                y: '-5',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '3',
                image: 'spaceport9',
            },
            'port2,-1': {
                y: '-1',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '2',
                image: 'spaceport9',
            },
            'port2,-2': {
                y: '-2',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '2',
                image: 'spaceport9',
            },
            'port2,-3': {
                y: '-3',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '2',
                image: 'spaceport9',
            },
            'port2,-4': {
                y: '-4',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '2',
                image: 'spaceport9',
            },
            'port2,-5': {
                y: '-5',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '2',
                image: 'spaceport9',
            },
            'port1,-1': {
                y: '-1',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '1',
                image: 'spaceport9',
            },
            'port1,-2': {
                y: '-2',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '1',
                image: 'spaceport9',
            },
            'port1,-3': {
                y: '-3',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '1',
                image: 'spaceport9',
            },
            'port1,-4': {
                y: '-4',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '1',
                image: 'spaceport9',
            },
            'port1,-5': {
                y: '-5',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '1',
                image: 'spaceport9',
            },
            'port-5,-3': {
                y: '-3',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-5',
                image: 'spaceport9',
            },
            'port-4,-3': {
                y: '-3',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-4',
                image: 'spaceport9',
            },
            'port-3,-3': {
                y: '-3',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-3',
                image: 'spaceport9',
            },
            'port-2,-3': {
                y: '-3',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-2',
                image: 'spaceport9',
            },
            'port-1,-3': {
                y: '-3',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-1',
                image: 'spaceport9',
            },
            'port0,-3': {
                y: '-3',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '0',
                image: 'spaceport9',
            },
            'port-5,-4': {
                y: '-4',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-5',
                image: 'spaceport9',
            },
            'port-4,-4': {
                y: '-4',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-4',
                image: 'spaceport9',
            },
            'port-3,-4': {
                y: '-4',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-3',
                image: 'spaceport9',
            },
            'port-2,-4': {
                y: '-4',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-2',
                image: 'spaceport9',
            },
            'port-1,-4': {
                y: '-4',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-1',
                image: 'spaceport9',
            },
            'port0,-4': {
                y: '-4',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '0',
                image: 'spaceport9',
            },
            'port-5,-5': {
                y: '-5',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-5',
                image: 'spaceport9',
            },
            'port-4,-5': {
                y: '-5',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-4',
                image: 'spaceport9',
            },
            'port-3,-5': {
                y: '-5',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-3',
                image: 'spaceport9',
            },
            'port-2,-5': {
                y: '-5',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-2',
                image: 'spaceport9',
            },
            'port-1,-5': {
                y: '-5',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '-1',
                image: 'spaceport9',
            },
            'port0,-5': {
                y: '-5',
                efficiency: '100',
                level: '30',
                name: 'Space Port',
                url: '/spaceport',
                x: '0',
                image: 'spaceport9',
            },
            ssla: {
                y: '5',
                efficiency: '100',
                level: '30',
                name: 'Space Station Lab',
                url: '/ssl',
                x: '4',
                image: 'ssla9',
            },
            sslb: {
                y: '5',
                efficiency: '100',
                level: '30',
                name: 'Space Station Lab',
                url: '/ssl',
                x: '5',
                image: 'sslb9',
            },
            sslc: {
                y: '4',
                efficiency: '100',
                level: '30',
                name: 'Space Station Lab',
                url: '/ssl',
                x: '5',
                image: 'sslc9',
            },
            ssld: {
                y: '4',
                efficiency: '100',
                level: '30',
                name: 'Space Station Lab',
                url: '/ssl',
                x: '4',
                image: 'ssld9',
            },
            intel: {
                y: '3',
                efficiency: '100',
                level: '30',
                name: 'Intel Training',
                url: '/intel',
                x: '4',
                image: 'inteltraining9',
            },
            mayhem: {
                y: '3',
                efficiency: '100',
                level: '30',
                name: 'Mayhem Training',
                url: '/mayhem',
                x: '5',
                image: 'mayhemtraining9',
            },
            politics: {
                y: '2',
                efficiency: '100',
                level: '30',
                name: 'Politics Training',
                url: '/politics',
                x: '4',
                image: 'politicstraining9',
            },
            theft: {
                y: '2',
                efficiency: '100',
                level: '30',
                name: 'Theft Training',
                url: '/theft',
                x: '5',
                image: 'thefttraining9',
            },
        },
    };
};

const empire_login = () => {
    return {
        session_id: 'this_is_a_session_id',
        status: get_status(),
    };
};

const empire_status = () => {
    return {
        id: '1',
        bodies: {
            colonies: [
                {
                    id: '1',
                    name: 'Earth',
                    x: '0',
                    y: '0',
                    orbit: 1,
                    empire_name: 'Rome',
                    empire_id: 1,
                },
            ],
            mystations: [
                {
                    id: '2',
                    name: 'Death Star',
                    x: '100',
                    y: '-50',
                    orbit: 2,
                    empire_name: 'Rome',
                    empire_id: 1,
                },
            ],
        },
        colonies: {
            '1': 'Earth',
        },
        rpc_count: 250,
        insurrect_value: 100000,
        is_isolationist: 0,
        name: 'Rome',
        status_message: 'Making the Lacuna Expanse a better Expanse',
        home_planet_id: '1',
        has_new_messages: 4,
        latest_message_id: 4,
        essentia: 521,
        next_colony_cost: 100000,
        next_station_cost: 1000000,
        planets: {
            '1': 'Earth',
            '2': 'Death Star',
        },
        tech_level: 30,
        self_destruct_active: 0,
        self_destruct_date: '',
        stations: {
            '2': 'Death Star',
        },
        primary_embassy_id: 100,
    };
};

const body_status = () => {
    return {
        id: 'id-goes-here',
        x: -4,
        y: 10,
        star_id: 'id-goes-here',
        star_name: 'Sol',
        orbit: 3,
        type: 'habitable planet',
        name: 'Earth',
        image: 'p35',
        size: 67,
        water: 900,
        ore: {
            gold: 3399,
            bauxite: 4000,
        },
        empire: {
            id: 'id-goes-here',
            name: 'Earthlings',
            alignment: 'ally',
            is_isolationist: 1,
        },
        station: {
            id: 'id-goes-here',
            x: 143,
            y: -27,
            name: 'The Death Star',
        },
        needs_surface_refresh: 0,
        building_count: 7,
        build_queue_size: 15,
        build_queue_len: 10,
        plots_available: 60,
        happiness: 3939,
        happiness_hour: 25,
        unhappy_date: '01 13 2014 16:11:21 +0600',
        neutral_entry: '01 13 2014 16:11:21 +0600',
        propaganda_boost: 20,
        food_stored: 33329,
        food_capacity: 40000,
        food_hour: 229,
        energy_stored: 39931,
        energy_capacity: 43000,
        energy_hour: 391,
        ore_hour: 284,
        ore_capacity: 35000,
        ore_stored: 1901,
        waste_hour: 933,
        waste_stored: 9933,
        waste_capacity: 13000,
        water_stored: 9929,
        water_hour: 295,
        water_capacity: 51050,
        skip_incoming_ships: 1,
        num_incoming_enemy: 0,
        num_incoming_ally: 0,
        num_incoming_own: 0,
        incoming_enemy_ships: [],
        incoming_ally_ships: [],
        incoming_own_ships: [],
    };
};

const server_status = () => {
    return {
        time: '2013 01 31 12:34:45 +0000', // lol
        version: '1.0',
        star_map_size: 500,
        rpc_limit: 10000,
    };
};

const get_status = () => {
    return {
        server: server_status(),
        empire: empire_status(),
        body: body_status(),
    };
};

const setupMocking = () => {
    console.log('Server mocking enabled');
    new Server({
        routes() {
            this.namespace = process.env.KA_SERVER_URL;

            this.post('/body', (_schema, response) => {
                const { method } = handleResponse('empire', response);
                switch (method) {
                    case 'get_buildings':
                        return { result: body_get_buildings() };
                    default:
                        console.error(`/body/${method} not handled`);
                        return {};
                }
            });

            this.post('/empire', (_schema, response) => {
                const { method } = handleResponse('empire', response);
                switch (method) {
                    case 'login':
                        return { result: empire_login() };
                    case 'logout':
                        return { logout: '1' };
                    case 'get_status':
                        return { result: get_status() };
                    default:
                        console.error(`/empire/${method} not handled`);
                        return {};
                }
            });
        },
    });
};

module.exports.setupMocking = setupMocking;
